// slug is kebab-case of game name
export type GameMeta = {
  slug: string
  name: string
  emoji: string
  tagline: string
  description: string
  howToPlay: string[]
  keywords: string[]
  category: string
}

export const GAMES_META: GameMeta[] = [
  {
    slug: 'heart-tap',
    name: 'Heart Tap',
    emoji: '💝',
    tagline: 'Tap hearts faster than your babe~',
    description: 'Heart Tap is a lightning-fast reaction game for couples. Hearts fall from the sky and you race to tap them before your partner does. The faster your reflexes, the more hearts you claim!',
    howToPlay: [
      'Hearts rain down on the screen',
      'Tap each heart as fast as you can',
      'Score more points than your partner to win',
      'Bigger hearts are worth more points!',
    ],
    keywords: ['heart tap couple game', 'kawaii tap game', 'reaction game for couples', 'tapping game online', 'heart game 2 player', 'couple mini game'],
    category: 'Reaction',
  },
  {
    slug: 'love-memory',
    name: 'Love Memory',
    emoji: '🃏',
    tagline: 'Find matching pairs before your partner!',
    description: 'Love Memory is a kawaii card-matching game for couples. Flip over pairs of adorable cards to find matches — the player with the best memory wins the most pairs and takes the round!',
    howToPlay: [
      'Cards are placed face-down on the grid',
      'Flip two cards on your turn to find a match',
      'Matched pairs are collected as points',
      'The player with the most pairs at the end wins',
    ],
    keywords: ['kawaii memory card game for couples', 'love memory game', 'couple card matching game', 'memory game 2 player', 'cute matching game online', 'flip card game couple'],
    category: 'Memory',
  },
  {
    slug: 'reflex-duel',
    name: 'Reflex Duel',
    emoji: '⚡',
    tagline: 'Who reacts first when lightning strikes?',
    description: 'Reflex Duel tests your raw reaction speed in a head-to-head battle. Wait for the signal and tap as fast as possible — even a millisecond can decide the winner in this kawaii couples duel!',
    howToPlay: [
      'Watch the screen and wait for the signal',
      'Tap the moment the signal appears',
      'Fastest reaction wins each round',
      'Best of multiple rounds decides the champion',
    ],
    keywords: ['reflex duel couples game', 'reaction speed game 2 player', 'kawaii reflex game', 'who reacts faster game', 'couple speed game online', 'lightning reflex mini game'],
    category: 'Reaction',
  },
  {
    slug: 'word-scramble',
    name: 'Word Scramble',
    emoji: '🔤',
    tagline: 'Unscramble kawaii words faster than bae~',
    description: 'Word Scramble challenges couples to unravel jumbled kawaii words as fast as possible. Race your partner to decode adorable Japanese-inspired words first and claim the word wizard title!',
    howToPlay: [
      'A scrambled kawaii word appears on screen',
      'Type the correct unscrambled word',
      'First player to type it correctly scores a point',
      'Most points after all rounds wins!',
    ],
    keywords: ['word scramble couple game', 'kawaii word game online', 'unscramble words 2 player', 'couple word game', 'japanese word scramble game', 'kawaii vocabulary game'],
    category: 'Quiz',
  },
  {
    slug: 'kawaii-quiz',
    name: 'Kawaii Quiz',
    emoji: '🧠',
    tagline: 'Test your kawaii knowledge together!',
    description: 'Kawaii Quiz puts your Japanese culture and cute trivia knowledge to the test in a competitive 2-player format. Answer questions about anime, sakura, mochi, and all things kawaii faster than your partner to win!',
    howToPlay: [
      'A trivia question about kawaii culture appears',
      'Both players race to select the correct answer',
      'First to tap the right answer scores the point',
      'Most correct answers at the end wins',
    ],
    keywords: ['kawaii quiz game for couples', 'japanese trivia couple game', 'anime quiz 2 player', 'cute trivia game online', 'kawaii knowledge game', 'couple trivia challenge'],
    category: 'Quiz',
  },
  {
    slug: 'target-pop',
    name: 'Target Pop',
    emoji: '🎯',
    tagline: 'Pop the target before your partner does!',
    description: 'Target Pop is a precision clicking game where couples compete to pop appearing targets as accurately and quickly as possible. Aim well, click fast, and outscore your partner in this kawaii bullseye challenge!',
    howToPlay: [
      'Targets pop up at random positions on screen',
      'Click or tap each target quickly and accurately',
      'Score points for each target you pop first',
      'The player with the most pops wins the round',
    ],
    keywords: ['target pop couple game', 'click accuracy game 2 player', 'kawaii target game online', 'couple aim game', 'pop targets mini game', 'precision game for couples'],
    category: 'Reaction',
  },
  {
    slug: 'math-race',
    name: 'Math Race',
    emoji: '🔢',
    tagline: 'Solve math faster and win the race~',
    description: 'Math Race turns mental arithmetic into a thrilling couples competition. Simple math equations appear on screen and you race to solve them faster than your partner — the sharper mind wins today!',
    howToPlay: [
      'A math equation appears for both players',
      'Calculate the answer in your head',
      'Enter the correct answer as fast as possible',
      'First to answer correctly scores a point',
    ],
    keywords: ['math race couple game', 'math speed game 2 player', 'arithmetic game for couples', 'mental math couple challenge', 'kawaii math game online', 'couple brain game'],
    category: 'Speed',
  },
  {
    slug: 'color-stroop',
    name: 'Color Stroop',
    emoji: '🎨',
    tagline: 'Can your brain beat the Stroop effect?',
    description: 'Color Stroop is a brain-bending couple game based on the famous Stroop effect. Color words are shown in mismatched ink colors — you must tap the ink color, not the word. Confusing and hilarious for couples!',
    howToPlay: [
      'A color word appears written in a different ink color',
      'Tap the button matching the INK COLOR (not the word)',
      'Answer faster than your partner to score',
      'Most correct fast answers wins the round',
    ],
    keywords: ['color stroop couple game', 'stroop effect game online', 'kawaii brain game', 'color word game 2 player', 'cognitive game for couples', 'mind trick game couple'],
    category: 'Quiz',
  },
  {
    slug: 'sakura-catch',
    name: 'Sakura Catch',
    emoji: '🌸',
    tagline: 'Catch falling sakura petals~ ✿',
    description: 'Sakura Catch is a serene yet competitive kawaii game where couples race to catch the most falling cherry blossom petals. Move your basket, avoid decoys, and catch more petals than your partner!',
    howToPlay: [
      'Sakura petals rain down from the top of the screen',
      'Move your basket left and right to catch them',
      'Avoid catching decoy items that reduce your score',
      'Catch the most petals to win!',
    ],
    keywords: ['sakura catch couple game', 'cherry blossom game 2 player', 'kawaii catch game', 'sakura mini game online', 'falling petals game couple', 'japanese couple game'],
    category: 'Reaction',
  },
  {
    slug: 'emoji-decode',
    name: 'Emoji Decode',
    emoji: '💬',
    tagline: 'Decode emoji messages before your babe!',
    description: 'Emoji Decode challenges couples to interpret fun emoji sequences and guess what they mean. Think fast and type the right answer before your partner — who is the ultimate emoji expert in your relationship?',
    howToPlay: [
      'A sequence of emojis representing a word or phrase appears',
      'Decode what the emojis mean',
      'Type the correct answer as fast as possible',
      'First to decode it correctly wins the point',
    ],
    keywords: ['emoji decode couple game', 'emoji quiz 2 player', 'guess the emoji game', 'kawaii emoji game online', 'couple emoji challenge', 'emoji riddle game'],
    category: 'Quiz',
  },
  {
    slug: 'simon-says',
    name: 'Simon Says',
    emoji: '🎵',
    tagline: 'Remember the pattern or lose the game~',
    description: 'Simon Says is a classic memory pattern game reimagined with kawaii flair for couples. Watch the light-up sequence, then repeat it perfectly. Longer sequences get trickier — see who can keep up the longest!',
    howToPlay: [
      'Watch the tiles light up in a specific sequence',
      'Repeat the exact sequence by tapping the tiles',
      'Each round the sequence gets one step longer',
      'The player who lasts the longest wins',
    ],
    keywords: ['simon says couple game', 'pattern memory game 2 player', 'kawaii simon game', 'sequence memory game online', 'light up pattern game couples', 'couple memory challenge'],
    category: 'Memory',
  },
  {
    slug: 'type-race',
    name: 'Type Race',
    emoji: '⌨️',
    tagline: 'Who types faster — you or your babe?',
    description: 'Type Race is the ultimate typing speed showdown for couples. Race to type kawaii words and phrases as fast and accurately as possible. The faster typist wins — time to find out who rules the keyboard!',
    howToPlay: [
      'A kawaii word or phrase appears on screen',
      'Type it out as quickly and accurately as possible',
      'Typos slow you down, so stay accurate',
      'First to complete the full text wins',
    ],
    keywords: ['type race couple game', 'typing speed game 2 player', 'kawaii typing game', 'typing competition online', 'couple typing challenge', 'who types faster game'],
    category: 'Speed',
  },
  {
    slug: 'rock-paper-sakura',
    name: 'Rock Paper Sakura',
    emoji: '✂️',
    tagline: 'Rock, Paper, Sakura — kawaii edition!',
    description: 'Rock Paper Sakura is a kawaii twist on the classic Rock Paper Scissors game for couples. Choose your symbol at lightning speed — but with a kawaii third option: Sakura! Play multiple rounds and find the champion.',
    howToPlay: [
      'Choose Rock, Paper, or Sakura each round',
      'Rock beats Sakura, Sakura beats Paper, Paper beats Rock',
      'Fast decisions matter — hesitate and you might lose!',
      'Most wins after all rounds is the champion',
    ],
    keywords: ['rock paper sakura couple game', 'kawaii rock paper scissors', 'rps game online 2 player', 'couple rps game', 'sakura game online', 'fun couple mini game'],
    category: 'Reaction',
  },
  {
    slug: 'star-catcher',
    name: 'Star Catcher',
    emoji: '🌟',
    tagline: 'Catch falling stars and wish together!',
    description: 'Star Catcher is a magical kawaii game where couples compete to collect the most falling stars. Move your character to catch stars as they rain down, but watch out for meteors that knock away your score!',
    howToPlay: [
      'Stars fall from the top of the screen',
      'Move left and right to catch as many as possible',
      'Avoid meteors that reduce your star count',
      'Collect the most stars to win the round',
    ],
    keywords: ['star catcher couple game', 'kawaii star game', 'catch falling stars 2 player', 'star mini game online', 'cute couple game stars', 'couple catching game'],
    category: 'Reaction',
  },
  {
    slug: 'number-rush',
    name: 'Number Rush',
    emoji: '🔢',
    tagline: 'Rush through numbers before your babe!',
    description: 'Number Rush is a rapid-fire number recognition game for couples. Numbers flash on screen and you must quickly identify if they match the target — fast judgment under pressure decides who wins this round!',
    howToPlay: [
      'A target number is shown at the top',
      'Numbers flash rapidly on screen',
      'Tap quickly when you see the target number',
      'Most correct taps without errors wins',
    ],
    keywords: ['number rush couple game', 'number recognition game 2 player', 'speed number game online', 'kawaii number game couples', 'math speed challenge', 'couple number game'],
    category: 'Speed',
  },
  {
    slug: 'koi-catch',
    name: 'Koi Catch',
    emoji: '🐟',
    tagline: 'Scoop the prettiest koi fish~',
    description: 'Koi Catch is a serene but competitive kawaii fishing game for couples. Race to scoop the correct colored koi fish as they swim across the pond — precision and speed both matter in this tranquil rivalry!',
    howToPlay: [
      'Colorful koi fish swim across the screen',
      'Scoop the specific koi color shown as the target',
      'Tap accurately — wrong fish costs you points',
      'Most correctly caught koi at the end wins',
    ],
    keywords: ['koi catch couple game', 'kawaii fishing game 2 player', 'koi fish game online', 'japanese koi game couple', 'scoop the fish game', 'cute fishing mini game'],
    category: 'Reaction',
  },
  {
    slug: 'balloon-pop',
    name: 'Balloon Pop',
    emoji: '🎈',
    tagline: 'Pop balloons, score points, win hearts!',
    description: 'Balloon Pop is a satisfying and addictive kawaii game for couples. Colorful balloons float upward and you race to pop the correct ones before your partner. Fast fingers and sharp eyes win this fluffy duel!',
    howToPlay: [
      'Balloons of various colors float upward',
      'Pop only the color indicated by the target',
      'Wrong balloon pops reduce your score',
      'Pop the most target balloons to win',
    ],
    keywords: ['balloon pop couple game', 'kawaii balloon game 2 player', 'pop balloons game online', 'couple balloon challenge', 'colorful pop game couples', 'cute mini game balloon'],
    category: 'Reaction',
  },
  {
    slug: 'sushi-swipe',
    name: 'Sushi Swipe',
    emoji: '🥢',
    tagline: 'Swipe the right sushi before it passes!',
    description: 'Sushi Swipe is a mouth-watering kawaii conveyor belt game for couples. Sushi plates glide past on a conveyor belt and you race to swipe the correct dish first. Hungry for victory? Show your partner your sushi skills!',
    howToPlay: [
      'Sushi plates move along a conveyor belt',
      'Swipe the specific sushi type shown as target',
      'Faster correct swipes earn more points',
      'The player who grabs the most right sushi wins',
    ],
    keywords: ['sushi swipe couple game', 'kawaii sushi game 2 player', 'conveyor belt sushi game', 'japanese food game couple', 'sushi mini game online', 'food game for couples'],
    category: 'Reaction',
  },
  {
    slug: 'lucky-spin',
    name: 'Lucky Spin',
    emoji: '🎰',
    tagline: 'Spin the wheel and test your luck together!',
    description: 'Lucky Spin adds a delightful element of chance to your couple gaming session. Spin the kawaii wheel and see what fate has in store — sometimes skill meets luck in this playful mini game for sweethearts!',
    howToPlay: [
      'Tap the wheel to spin it at full force',
      'Stop the wheel at the right moment to land on bonuses',
      'Each spot on the wheel gives different point values',
      'Highest total after all spins wins the round',
    ],
    keywords: ['lucky spin couple game', 'kawaii wheel spin game', 'spin the wheel 2 player', 'luck game for couples', 'kawaii fortune game online', 'couple luck challenge'],
    category: 'Speed',
  },
  {
    slug: 'lightning-tile',
    name: 'Lightning Tile',
    emoji: '⚡',
    tagline: 'Strike the glowing tile in a flash!',
    description: 'Lightning Tile is an electrifying kawaii tile-tapping game for couples. Tiles light up randomly and both players race to tap them first — split-second reflexes separate the champion from the runner-up!',
    howToPlay: [
      'A grid of tiles appears on screen',
      'Tiles light up one at a time randomly',
      'Tap the lit tile before your partner does',
      'Most tiles tapped first wins the game',
    ],
    keywords: ['lightning tile couple game', 'tile tapping game 2 player', 'kawaii reflex tile game', 'glowing tile game online', 'reaction tile game couples', 'fast tap mini game'],
    category: 'Reaction',
  },
  {
    slug: 'bell-race',
    name: 'Bell Race',
    emoji: '🔔',
    tagline: 'Ring the bell first when it appears~',
    description: 'Bell Race is a deceptively simple yet thrilling reaction game for couples. A kawaii bell appears on screen at random intervals — the first player to ring it scores the point. Timing and alertness are everything!',
    howToPlay: [
      'Watch the screen carefully for the bell to appear',
      'The moment the bell appears, tap it immediately',
      'Do not tap before the bell appears or you lose a point',
      'Ring the most bells to win the round',
    ],
    keywords: ['bell race couple game', 'ring the bell game 2 player', 'kawaii reaction game', 'bell timing game online', 'couple alertness game', 'reaction game for sweethearts'],
    category: 'Reaction',
  },
  {
    slug: 'cat-whack',
    name: 'Cat Whack',
    emoji: '🐾',
    tagline: 'Whack the mischievous cats~ (=^・ω・^=)',
    description: 'Cat Whack is a kawaii take on whack-a-mole where mischievous cats pop out of holes competing for your attention. Tap the cats faster than your partner in this adorably competitive couple game!',
    howToPlay: [
      'Mischievous cats pop out of holes at random',
      'Tap each cat as quickly as possible to score',
      'Some cats are worth more points than others',
      'Most cats whacked in the time limit wins',
    ],
    keywords: ['cat whack couple game', 'kawaii whack a mole game', 'cat tapping game 2 player', 'whack a cat game online', 'cute mole game couples', 'kawaii cat mini game'],
    category: 'Reaction',
  },
  {
    slug: 'dango-stack',
    name: 'Dango Stack',
    emoji: '🍡',
    tagline: 'Stack the dango as high as you can~',
    description: 'Dango Stack is a balance-focused kawaii stacking game for couples. Stack as many sweet dango treats as possible without toppling the pile. Perfect timing beats your partner and crowns the dango stacking champion!',
    howToPlay: [
      'Dango pieces swing back and forth on screen',
      'Tap at the right moment to stack each piece',
      'Stack them as straight as possible to avoid collapse',
      'Whoever stacks the most before toppling wins',
    ],
    keywords: ['dango stack couple game', 'kawaii stacking game 2 player', 'japanese food stack game', 'cute stacking mini game', 'couple balance game online', 'dango mini game'],
    category: 'Speed',
  },
  {
    slug: 'mochi-smash',
    name: 'Mochi Smash',
    emoji: '🪅',
    tagline: 'Smash the mochi before your partner!',
    description: 'Mochi Smash is a satisfying and competitive kawaii game for couples. Round, bouncy mochi pop up and you race to smash as many as possible. The player with the biggest smash count wins this bouncy battle!',
    howToPlay: [
      'Round mochi pop up at random positions',
      'Tap and smash each mochi as fast as possible',
      'Bonus mochi are worth extra points — look out!',
      'Most mochi smashed in the time wins',
    ],
    keywords: ['mochi smash couple game', 'kawaii mochi game 2 player', 'smash mochi game online', 'cute smashing game couples', 'tap and smash mini game', 'japanese sweet game couple'],
    category: 'Reaction',
  },
  {
    slug: 'dart-toss',
    name: 'Dart Toss',
    emoji: '🎯',
    tagline: 'Aim true and outscore your babe~',
    description: 'Dart Toss challenges couples to show off their aim in a kawaii carnival-style throwing game. Time your throw and release at the perfect moment to land near the bullseye and beat your partner\'s score!',
    howToPlay: [
      'A dart moves toward the target automatically',
      'Tap at the right moment to throw it at the bullseye',
      'Closer to center means more points',
      'Best combined score across all throws wins',
    ],
    keywords: ['dart toss couple game', 'kawaii dart game 2 player', 'aim game online couples', 'throw dart mini game', 'carnival game for couples', 'bullseye game couple'],
    category: 'Speed',
  },
  {
    slug: 'odd-one-out',
    name: 'Odd One Out',
    emoji: '🃏',
    tagline: 'Spot the odd one out first~',
    description: 'Odd One Out tests your visual observation skills in a head-to-head couple challenge. Spot the item that doesn\'t belong in a group of kawaii characters — the sharper eye wins each round of this cute couple game!',
    howToPlay: [
      'A group of similar kawaii items appears on screen',
      'One item is slightly different from the rest',
      'Tap the odd one out as fast as you can',
      'First to correctly identify it scores the point',
    ],
    keywords: ['odd one out couple game', 'spot the difference game 2 player', 'kawaii observation game', 'find the odd one game online', 'visual challenge couple', 'spot it game couples'],
    category: 'Quiz',
  },
  {
    slug: 'number-sequence',
    name: 'Number Sequence',
    emoji: '🔢',
    tagline: 'Complete the number pattern first!',
    description: 'Number Sequence is a pattern recognition challenge for couples. Identify what number comes next in a sequence and input it faster than your partner — a quick analytical mind wins this kawaii brain battle!',
    howToPlay: [
      'A sequence of numbers with a missing element appears',
      'Figure out the pattern to determine the missing number',
      'Type or select the correct answer quickly',
      'First to answer correctly wins the point',
    ],
    keywords: ['number sequence couple game', 'pattern recognition game 2 player', 'kawaii number puzzle game', 'sequence game online', 'couple brain challenge numbers', 'number pattern game'],
    category: 'Quiz',
  },
  {
    slug: 'color-match',
    name: 'Color Match',
    emoji: '🎨',
    tagline: 'Match colors faster than your partner~',
    description: 'Color Match is a vibrant couple game where you race to identify and match specific color combinations. Quick color perception and fast reflexes help you outscore your partner in this kawaii palette challenge!',
    howToPlay: [
      'A target color combination is shown',
      'Tap the matching color from the options below',
      'Wrong taps waste precious time',
      'Most correct matches in the time limit wins',
    ],
    keywords: ['color match couple game', 'kawaii color game 2 player', 'color matching game online', 'match colors fast game', 'couple color challenge', 'visual color game for couples'],
    category: 'Reaction',
  },
  {
    slug: 'tic-tac-toe',
    name: 'Tic Tac Toe',
    emoji: '⭕',
    tagline: 'Outsmart bae in 3 rounds of X vs O!',
    description: 'Tic Tac Toe gets a kawaii makeover! Play live against your partner in a best-of-3 match. X always goes first, turns alternate in real time. Claim the most rows, columns, or diagonals to win the battle!',
    howToPlay: [
      'Player 1 is X, Player 2 is O — X always goes first',
      'Tap a square on your turn to place your symbol',
      'Get three in a row (horizontal, vertical, diagonal) to win a round',
      'Best of 3 rounds wins the mini-game!',
    ],
    keywords: ['tic tac toe couple game', 'kawaii tic tac toe online', 'noughts and crosses 2 player', 'couple game tic tac toe', 'x and o game cute', 'multiplayer tic tac toe'],
    category: 'Strategy',
  },
  {
    slug: 'quick-count',
    name: 'Quick Count',
    emoji: '📊',
    tagline: 'Count faster than your partner can blink!',
    description: 'Quick Count is a fast-paced counting challenge for couples. Objects flash on screen briefly and you must count them accurately and quickly. Sharper eyes and a speedier count wins this kawaii couple showdown!',
    howToPlay: [
      'A group of kawaii objects flashes on screen briefly',
      'Count them as fast as possible',
      'Enter your count before the timer runs out',
      'Most accurate and fastest counts across rounds wins',
    ],
    keywords: ['quick count couple game', 'counting game 2 player', 'kawaii counting challenge', 'speed count game online', 'fast counting game couples', 'subitizing game couple'],
    category: 'Speed',
  },
]

export function getGameBySlug(slug: string): GameMeta | undefined {
  return GAMES_META.find((g) => g.slug === slug)
}
